substitutions:
  _IMAGE_NAME: gcr.io/$PROJECT_ID/bh-fe-final:latest
  _CLOUD_RUN_SERVICE: bh-fe-final
  _REGION: europe-west1
  _DOCKERFILE: Dockerfile
  _BUILD_CONTEXT: .
  _VITE_API_BASE_URL: https://api.biohax.pro

steps:
  - id: Build frontend image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    env:
      - DOCKER_BUILDKIT=1
    secretEnv:
      - VITE_GOOGLE_CLIENT_ID
    args:
      - -c
      - |
        set -euo pipefail
        docker build \
          --build-arg VITE_GOOGLE_CLIENT_ID="$$VITE_GOOGLE_CLIENT_ID" \
          --build-arg VITE_API_BASE_URL=$_VITE_API_BASE_URL \
          -t $_IMAGE_NAME \
          -f $_DOCKERFILE \
          $_BUILD_CONTEXT

  - id: Push image to registry
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_IMAGE_NAME

  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_CLOUD_RUN_SERVICE
      - --image
      - $_IMAGE_NAME
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated
      - --project
      - $PROJECT_ID
      - --quiet

images:
  - $_IMAGE_NAME

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/google-client-id/versions/latest
      env: VITE_GOOGLE_CLIENT_ID

