steps:
  - id: Build frontend image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    env:
      - DOCKER_BUILDKIT=1
    secretEnv:
      - VITE_GOOGLE_CLIENT_ID
    args:
      - -c
      - |
        set -euo pipefail
        docker build \
          --build-arg VITE_GOOGLE_CLIENT_ID="$$VITE_GOOGLE_CLIENT_ID" \
          --build-arg VITE_API_BASE_URL=https://bh-backend-final-714223448245.europe-west1.run.app \
          -t gcr.io/$PROJECT_ID/bh-fe-final:latest \
          -f Dockerfile \
          .

  - id: Push image to registry
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/bh-fe-final:latest

  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - bh-fe-final
      - --image
      - gcr.io/$PROJECT_ID/bh-fe-final:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --project
      - $PROJECT_ID
      - --quiet

images:
  - gcr.io/$PROJECT_ID/bh-fe-final:latest

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/google-client-id/versions/latest
      env: VITE_GOOGLE_CLIENT_ID

