steps:
  - id: Build backend image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    env:
      - DOCKER_BUILDKIT=1
    args:
      - -c
      - |
        set -euo pipefail
        docker build \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/production/bh-backend-final:latest \
          -f backend/Dockerfile \
          backend

  - id: Push image to registry
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/$PROJECT_ID/production/bh-backend-final:latest

  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - bh-backend-final
      - --image
      - europe-west1-docker.pkg.dev/$PROJECT_ID/production/bh-backend-final:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --add-cloudsql-instances
      - $PROJECT_ID:europe-west1:biohax-main-postgres
      - --service-account
      - codexjesus@biohax-777.iam.gserviceaccount.com
      - --set-env-vars
      - >-
        NODE_ENV=production,
        GCP_PROJECT_ID=$PROJECT_ID,
        CORS_ORIGIN=https://biohax.pro https://staging.biohax.pro http://localhost:5173 http://localhost:3000 http://127.0.0.1:5173 http://127.0.0.1:3000,
        WHOOP_REDIRECT_URI=https://biohax.pro/oauth/whoop/callback,
        WHOOP_TOKEN_KEY_ID=whoop-token-key-v1,
        AUTH_ACCESS_TOKEN_TTL_SECONDS=900,
        AUTH_REFRESH_TOKEN_TTL_SECONDS=2592000,
        DASHBOARD_CACHE_TTL_SECONDS=300,
        DASHBOARD_SNAPSHOT_TTL_SECONDS=900,
        SECRET_REFRESH=1763211958,
        WHOOP_WEBHOOK_SECRET=f8072c6f57878988bb47970e1ceb25ba7265bc6856e7b293070d808df4abb381414d183378efc3e5d767a45ce34d1b9f25955d4afaced9c60b9cf83726446c22,
        WHOOP_AUTHORIZE_URL=https://api.prod.whoop.com/oauth/oauth2/auth,
        LAB_UPLOAD_KMS_KEY_NAME=projects/biohax-777/locations/europe-west1/keyRings/lab-upload/cryptoKeys/lab-upload-data
      - --set-secrets
      - >-
        DATABASE_URL=database-url:latest,
        JWT_SECRET=jwt-secret:latest,
        AUTH_REFRESH_ENCRYPTION_KEY=auth-refresh-encryption-key:latest,
        OPENROUTER_API_KEY=OPENROUTER_API_KEY:latest,
        WHOOP_CLIENT_ID=whoop-client-id:latest,
        WHOOP_CLIENT_SECRET=whoop-client-secret:latest,
        WHOOP_TOKEN_ENCRYPTION_KEY=whoop-token-encryption-key:latest,
        GOOGLE_CLIENT_ID=google-client-id:latest,
        GOOGLE_CLIENT_SECRET=google-client-secret:latest,
        SUPER_ADMIN_PASSWORD=super-admin-password:latest,
        STRAVA_CLIENT_SECRET=strava_client_secret:latest,
        STRAVA_ACCESS_TOKEN=strava_access_token:latest,
        STRAVA_REFRESH_TOKEN=strava_refresh_token:latest,
        STRAVA_TOKEN_ENCRYPTION_KEY=strava-token-encryption-key:latest,
        LAB_UPLOAD_SEALING_KEY=lab-upload-sealing-key:latest
      - --project
      - $PROJECT_ID
      - --quiet

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/production/bh-backend-final:latest

